export const BUSINESS_TYPES: string[] = [
  'Landscaping',
  'Storage units',
  'Plumbing',
  'HVAC',
  'Roofing',
  'Lawn care',
  // 'Painting services',
  // 'Auto repair',
  // 'Electrician services',
  // 'Carpentry',
  // 'Cleaning services',
  // 'Pest control',
  // 'Window cleaning',
  // 'Dry cleaning',
  // 'Moving services',
  // 'Childcare services',
  // 'Pet grooming',
  // 'Pool cleaning',
  // 'Handyman services',
  // 'Locksmith services',
  // 'Massage therapy',
  // 'Fitness classes',
  // 'Dance instruction',
  // 'Music lessons',
  // 'Florist services',
]
